// src/data.js

const products = [
  {
    id: 1,
    name: "Muffler",
    price: 1200,
    description: "Soft wool muffler perfect for winter.",
    image: "/assets/img/muffler.png",
    category: "Clothing",
  },
  {
    id: 2,
    name: "Leather Jacket",
    price: 4500,
    description: "Stylish black leather jacket.",
    image: "/assets/img/leather-jacket.png",
    category: "Clothing",
  },
  {
    id: 3,
    name: "Sports Shoes",
    price: 3200,
    description: "Comfortable running shoes with great grip.",
    image: "/assets/img/shoes.png",
    category: "Footwear",
  },
  {
    id: 4,
    name: "Smart Watch",
    price: 5200,
    description: "Fitness tracking smartwatch with heart rate monitor.",
    image: "/assets/img/smartwatch.png",
    category: "Electronics",
  },
  {
    id: 5,
    name: "Bluetooth Headphones",
    price: 2800,
    description: "Wireless headphones with noise cancellation.",
    image: "/assets/img/headphones.png",
    category: "Electronics",
  },
  {
    id: 6,
    name: "Backpack",
    price: 1800,
    description: "Durable backpack with multiple compartments.",
    image: "/assets/img/backpack.png",
    category: "Accessories",
  },
  {
    id: 7,
    name: "Sunglasses",
    price: 900,
    description: "Stylish UV-protected sunglasses.",
    image: "/assets/img/sunglasses.png",
    category: "Accessories",
  },
  {
    id: 8,
    name: "Gaming Mouse",
    price: 2500,
    description: "High precision wired gaming mouse with RGB lights.",
    image: "/assets/img/mouse.png",
    category: "Electronics",
  },
  {
    id: 9,
    name: "Mechanical Keyboard",
    price: 4200,
    description: "RGB backlit mechanical keyboard for gamers.",
    image: "/assets/img/keyboard.png",
    category: "Electronics",
  },
  {
    id: 10,
    name: "Water Bottle",
    price: 500,
    description: "Insulated stainless steel water bottle.",
    image: "/assets/img/bottle.png",
    category: "Home & Kitchen",
  },
  {
    id: 11,
    name: "Yoga Mat",
    price: 1500,
    description: "Non-slip yoga mat for daily workouts.",
    image: "/assets/img/yogamat.png",
    category: "Fitness",
  },
  {
    id: 12,
    name: "Wireless Charger",
    price: 2000,
    description: "Fast charging pad for smartphones and earbuds.",
    image: "/assets/img/charger.png",
    category: "Electronics",
  },
];

export default products;
